spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=true;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;;NON_KEYWORDS=user;
      username: sa
      password: sa1234!
      driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:init.sql

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug
